name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Run linter and formatter
        run: pnpm lint
      - name: Check
        run: pnpm check
      - name: Install Playwright Browsers
        run: npx playwright install
      - name: Run E2E Test
        run: pnpm test
      - name: Build
        run: pnpm build
